### ISSUE TITLE
Update account layout to be mobile friendly.

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#133]
**Problem/Why**

The accountlayout sidebar takes up good deal of screen real estate on mobile.

![image.png](https://images.zenhubusercontent.com/5fe17935da86cae135bcd2ab/012cfa78-09b9-4820-ab2e-589578dec73c)

---

**Goal/What**

The account layout sidebar should be restructured on mobile to take up less vertical real estate.  A **naive** suggestion of how that may be accomplished: 
![image.png](https://images.zenhubusercontent.com/5fe17935da86cae135bcd2ab/fe1f50bb-c6e0-4849-801b-c8f4d44733db)

---

**Solution/How**

- [ ] Update `layouts/AccountLayout.vue` to make the page mobile friendly.

### Review Checklist

- [ ]  Mobile friendly interface

**Comment by wreality** [comment]
@gmeben I updated the description with what was in my head for this one. Refinements welcome, this is quite literally just what's in my head and my head is full of all kinds of silly things.

**Comment by gmeben** [comment]
@wreality There's no Quasar-native CSS breakpoint for handling screen real estate less than 600 pixels. We can't do a two column layout between 400 and 600 pixels width without creating a custom breakpoint. Because we're using a framework, I'm apprehensive about creating a custom breakpoint for this.

**Comment by wreality** [comment]
Why wouldn't we want this layout below 600? Why the focus on 400?

**Comment by gmeben** [comment]
@wreality We want this layout between 400 and 600 pixels is because that's the screen width range that can comfortably support this two column layout. At 400 pixels and less (iPhone), this cannot be represented in two columns because there's not enough room. We have to use one column at that breakpoint.

**Comment by gmeben** [comment]
Scratch that! I took another stab at it and this can be represented in a two column layout around 400 pixels and it fits comfortably. I must've done something differently before and mistakenly had the takeaway that this wasn't feasible. 

<img width="498" alt="screenshot of a two column layout successfully achieved at iPhone resolution" src="https://user-images.githubusercontent.com/2668987/108867471-3a2c8200-75c3-11eb-98bb-b55530b5f8ec.png">

**Comment by wreality** [comment]
This work was incorporated into #132
