### ISSUE TITLE
Create Scalable Process for Copywriting

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1331]
### Problem/Why
Currently, the majority of the copy for language that appears throughout the application is largely authored by developers and may not be suitable for a production release. Additionally, not all of this copy is handled by the i18n translation functionality on the frontend, either. It is currently difficult to identify all the locations throughout the application where i18n.js-derived text appears. As the application evolves, the composition of text throughout the application will change as well. This presents challenges for copyeditors to contribute copywriting in both the short-term and the long-term. 

### Goal/What
Create a way to automatically generate screenshots of each page of the application that show the page with and without i18n.js text provided. 

### Solution/How
Update Cypress GitHub action.

**Comment by gmeben** [comment]
Remaining pages with issues

* Register
    - Footer appears twice and obstructs page
* Submission Review
    - Missing the remainder of the page beneath the fold; QLayout might be to blame
* Basic Setup
    - VQInput translated strings don't render
* Account Metadata
    - VQInput translated strings don't render
* Profile
    - VQInput translated strings don't render

**Comment by wreality** [comment]
OK, so register I'll fix by making the footer non-sticky.  Also, of note, it only appears on register/login because the footer doesn't appear anywhere else in the application #oops

Submission review is totally the QLayout, I suggest we defer fixing this one until we get that page broken out of the QLayout because any work to hack this to work currently is just going to be moot then.

VQInputs are fixed as well.
