### ISSUE TITLE
Reuse/Create a GraphQL endpoint to search users and fill the dropdown on the manage submissions page

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#495]
### Problem/Why

The users dropdown on the manage submissions page does not display users in the application.

### Goal/What
The users dropdown populates and filters users in the application.

### Solution/How
Use the existing GraphQL endpoint or create a new one to power the user search dropdown. The dropdown filters the users as text is entered.

### To Do / Acceptance Criteria

- [x] The dropdown search the db and returns real users.
- [x] Jest and Cypress tests exists.

### Review Checklist

- [ ] Jest and PHP unit tests pass.

### Accessibility Checklist

- [ ] Passes axe accessibility checks

**Comment by Sruthin86** [comment]
**Work completed**
- Updated the queries.js to include a query for searching users with a search term.
- Updated the `scout` configs to enable fuzzy searching
- Updated `SubmissionDetails.vue` to populate the autocomplete dropdown with users from db

**Work remaining**
- The frontend dropdown filtering users upon input.
- Jest and cypress tests.

**Comment by gmeben** [comment]
I was able to get indexing working on the users table, which enables filtering of the dropdown upon user input. I discovered the `Searchable` trait was already applied to the `Users` model. 

All I had to do was:

1. Run `Lando artisan scout:import App\\Models\\User` in the CLI
2. Launch Tinker and generate 120 users with `User::factory()->count(120)->create();`.

Typing various bits of text in the search input seems to filter results correctly.

**Comment by gmeben** [comment]
In implementing the new assertion in the Cypress test, I came across an accessibility violation detected by axe-core 4.3.2 that complains about a "region" a11y error. I believe that refers to this: https://dequeuniversity.com/rules/axe/4.3/scrollable-region-focusable

When I attempt to check this page within the latest Chrome extension version of axe DevTools (4.12.2), it does not detect any errors, presumably because it uses axe-core 4.3.1.

This may be an issue that axe-core takes with Quasar that we won't be able to mitigate or may become a non-issue as axe-core continues to evolve (as we've seen before with "nested-interactive" a11y errors).

For now, I'm choosing to disable the 'region' error for the a11y check at the end of this new assertion.

**Comment by gmeben** [comment]
Sruthin discovered that the actual a11y error that's being encountered is this: https://dequeuniversity.com/rules/axe/4.3/region

This is because the dropdown that represents the QSelect's results is injected to the markup outside of a landmark element (ex: `main`) and is not given a role. There doesn't appear to be a way to add a `role` attribute to this injected element. This error is most likely going to need to be resolved by the maintainers of Quasar.
