### ISSUE TITLE
Obtain Metadata from PPJ Editorial Team

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#64]
**Problem/Why**

The current understanding of what information might be necessary to represented on profiles in CCR.

---

**Goal/What**

We need to know what information the application should store and which role should have the right to change each field

---

**Solution/How**

Create a list of fields needed, what information they would contain, and who has edit rights

--- 
### To Do 
- [x] Potentially look at other systems, such as Humanities Commons, to see what other data their profiles contain 
- [x] Mine the Matrix system to see what is being captured in the current PPJ/FPR system. 
- [x] Meet with PPJ Editorial team to learn which fields they would like to have in the application. 
### Review Checklist 
- [x] review the list of fields to verify there aren't duplicates 
- [x] review the list of fields to make sure they are able to be implemented 
- [x] review the list of fields to make sure they make sense 
- [x] review the list of fields to make sure nothing is missing 
 
> Trello Source: https://trello.com/c/lo1NZiiX

**Comment by sattler9** [comment]
A [google sheet ](https://docs.google.com/spreadsheets/d/1-20-K7TNzajTfhNBRCEX0JM48yLXzshyL5OkFiD4coo/edit?usp=sharing)was set up with a start on the fields desired for a user profile. It has been shared with the PPJ editorial team through Teams on Jan. 13, 2021 and with the CCR dev team via Teams on Jan. 11, 2021. It contains also thoughts on whether the fields should be required or not and how they are populated.

**Comment by amareshjoshi** [comment]
I added a page to the google sheet listing the user metadata.

The PPJ database only has usable metadata fields on people,
other categories are not available:

- review statistics
- timeliness statistics
- other metrics

The reason is the legacy PPJ system did not collect these
successfully. Either the features that used these fields were buggy and therefore
abandoned, or they were planned but never implemented.
