### ISSUE TITLE
Upgrade backend to Laravel 9

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#908]
### Problem/Why
The application is not running the latest version of the Laravel framework. 

### Goal/What
Upgrade the Laravel dependency to Laravel v9

### Solution/How
@wreality has already reviewed the [upgrade guide](https://laravel.com/docs/9.x/upgrade).  There are no obvious blockers to upgrading.

### To Do / Acceptance Criteria

- [x] Upgrade dependencies following the upgrade guide
- [x] Remove the ignition dep rather than upgrading as the application doesn't use HTML errors

### Review Checklist

- [x] Tests pass

### Accessibility Checklist
No accessibility considerations. Backend only.

**Comment by gmeben** [comment]
I completed the Overview of Human Research Protection training.

In my interpretation of the program, it appears the usability testing we intend to conduct will not meet the definition of "research" as defined by HRPP because the knowledge produced by this testing will be highly specific to the application and will not be generalizable. From slide 16: 

>Research means a systematic investigation, including research development, testing and evaluation, designed to develop or contribute to generalizable knowledge.

However, the usability testing we intend to conduct will involve human subjects as defined by HRPP. From slide 17:

>Human subject means a living individual about whom an investigator (whether professional or student) conducting research:
(i) Obtains information or biospecimens through intervention or interaction with the individual, and uses, studies, or analyzes the information or biospecimens; or
(ii) Obtains, uses, studies, analyzes, or generates identifiable private information or identifiable biospecimens.


This means a limited IRB review may be applicable. From slide 20:

>...exempt research is not exempt from protection of human participants and application of the ethical principles outlined in the Belmont Report such as informed consent, equitable selection, and risk/benefit assessment.

>Limited IRB Review

>To qualify for an exemption that requires limited IRB review, the IRB must conduct a limited IRB review to assure certain requirements are met (e.g. adequate provisions to protect the privacy of subjects and to maintain the confidentiality of data, broad consent). These studies require submission of modifications for any changes that impact the limited IRB review requirements (e.g. privacy, confidentiality).

>Requests for an exempt determination are made through an application for an initial study that is submitted to the MSU IRB by the PI through the MSU IRB Online Application System.
